GET http://localhost:5000/api/services

### Get Services
GET http://localhost:5000/api/services

### Get Mechanics
GET http://localhost:5000/api/mechanics

### Get Bookings
GET http://localhost:5000/api/bookings

### Create Booking
POST http://localhost:5000/api/bookings
Content-Type: application/json

{
  "customerName": "Customer 11",
  "bikeModel": "Activa",
  "serviceId": "6a1e8b9826919aa89e6e2ce4"
}